---
# tasks file for roles/osp-instance-delete
- name: OpenStack servers
  os_server_facts:
   cloud: ospcloud
   server: 'frontend'
  register: openstack_info

- name: Deleting openstack servers
  os_server:
    name: "{{ item.id }}"
    state: absent
  loop: "{{ openstack_info.ansible_facts.openstack_servers }}"
